<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Customer\Subscriptions
 */
?>

<div id="sp-widget-mysubscriptions">
    The my subscriptions widget is loading.
</div>

<script>
    window.subscriptionWidgetConfig = '<?php echo $block->getSubscriptionWidgetConfiguration(); ?>';
</script>

<script src="http://10.2.1.145:8081/subscribepro-widgets.min.js"></script>

<script>
    // Setup config for Subscribe Pro
    var widgetConfig = {
        widgetElementId: 'sp-widget-mysubscriptions',
        apiBaseUrl: window.subscriptionWidgetConfig.apiBaseUrl,
        apiAccessToken: window.subscriptionWidgetConfig.apiAccessToken,
        spreedlyEnvironmentKey: window.subscriptionWidgetConfig.spreedlyEnvironmentKey,
        customerId: window.subscriptionWidgetConfig.customerId
    };
    // Call init
    subscribepro.widgets.init('mysubscriptions', widgetConfig);
</script>

