<?php
/**
 * @var $block \Swarming\SubscribePro\Block\Customer\Subscriptions
 */
?>

<div id="sp-widget-mysubscriptions">
    The my subscriptions widget is loading.
</div>

<script>
    window.customerData = <?php echo \Zend_Json::encode($block->getCustomerData()); ?>;
console.log(window.customerData);
    window.apiAccessToken = '<?php echo $block->getApiAccessToken(); ?>';
</script>

<script src="http://10.2.1.145:8081/subscribepro-widgets.min.js"></script>

<script>
    // Setup config for Subscribe Pro
    var widgetConfig = {
        widgetElementId: 'sp-widget-mysubscriptions',
        apiBaseUrl: 'https://api.subscribepro.com',
        apiAccessToken: window.apiAccessToken,
        spreedlyEnvironmentKey: 'testtesttest',
        customerId: '768421'
    };
    // Call init
    subscribepro.widgets.init('mysubscriptions', widgetConfig);
</script>

